### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by bernalhd** [irazoquimatias/PI_UNRaf_2023#1]
### Tasks

- [ ] Develop backend.
- [ ] Develop frontend.

### Additional Notes

**Comment by irazoquimatias** [comment]
- [x] Make inputs as parameters (see "scripts/parse_fastq.py" as example of parse_options)
- [x] When a synonymous mutation is found, the output should show the nucleotide that's different, not the amino acid
- [x] Add sequence pairwise alignment (Bio.Align.PairwiseAligner if it's not very slow). Script should take each sequence from a multifasta, align it against the reference and then look for mutations in that alignment.
- [ ] Make old scripts more "pythonish" (this one's on me, styles should be the same in all scripts).
- [ ] Add mutations script to "make_consensus".
- [ ] Add script to check every file format (not the extension) at start of "make_consensus"?
- [ ] Find cool name for tool.
- [ ] Add test data and test everything.
